---
title: Een functie maken en aanroepen
hero_image: images/banner.png
description: Hoe je een functie in MakeCode maakt en aanroept
version: 4
listed: false
copyedit: false
last_tested: "2023-09-19"
steps:
  - title: Inleiding
