title: Δημιούργησε και κάλεσε μία συνάρτηση
hero_image: images/banner.png
description: Πώς να δημιουργήσεις και να καλέσεις μια συνάρτηση στο MakeCode
version: 4
listed: false
copyedit: false
last_tested: "2023-09-19"
steps:
  - 
    title: Εισαγωγή
