title: Create and call a function
hero_image: images/banner.png
description: How to create and call a function in MakeCode
version: 4
listed: false
copyedit: false
last_tested: "2023-09-19"
steps:
  - 
    title: Introduction
