---
title: Créer et appeler une fonction
hero_image: images/banner.png
description: Comment créer et appeler une fonction dans MakeCode
version: 4
listed: false
copyedit: false
last_tested: "2023-09-19"
steps:
  - title: Introduction
